"""empty message

Revision ID: e02586f98590
Revises: 
Create Date: 2023-04-20 18:13:11.736578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02586f98590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_reference_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_user_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('creation_time', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('delinquent', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('account_balance', sa.String(length=64), nullable=True),
    sa.Column('paid_type', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymentuser')
    # ### end Alembic commands ###
